services:
  bg-changer:
    image:  washuu/background-changer:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 3
  
  bmi-index:
    image: washuu/bmi-index:latest
    ports:
      - "8081:80"
    deploy:
      replicas: 3

  digital-clock:
    image: washuu/digital-clock:latest
    ports:
      - "8082:80"
    deploy:
      replicas: 3
  currency-converter:
    image: washuu/currency-converter:latest
    ports:
      - "8083:80"
    deploy:
      replicas: 3
  tik-tak-toe:
    image: washuu/tik-tak-toe:latest
    ports:
      - "8084:80"
    deploy:
      replicas: 3